### ISSUE TITLE
MEDIUM PRIORITY - Oleksandr to write function updateHTML_WithStars

### ISSUE THREAD

**Issue by timsbootcamp** [timsbootcamp/meow-finder#12]
Oleksandr to write function updateHTML_WithStars that takes parameter of a number  

if number >85 then  	
     update html with *****  

elseif number >70 	
     update html with ****  

elseif number >60 	
     update html with ***  

elseif number >50 	
    update html with **  

elseif number >10 	
    update html with *
else
    update with ''

**Comment by Khomych1004** [comment]
the function has been created. added to the code. tested. uploaded to git. added to master branch in git
