### ISSUE TITLE
MEDIUM PRIORITY - Tidy up code

### ISSUE THREAD

**Issue by timsbootcamp** [timsbootcamp/meow-finder#38]
1. In api2.js, can you change your constant names to the ones below :

const apiKey_TheCatAPI = 
const baseUrl_TheCatAPI = 

2. Can you change the name of api2.js to 'api-thecat.js'

3. At top of your js file, can you add the comment :

// 'api-thecat.js' holds all Javascript related to accessing 'theCatAPI'

**Comment by Khomych1004** [comment]
I updated all the names and uploaded everything into Git. 
you need to replace
 <script src="./assets/js/api2.js"></script> with <script src="./assets/js/api-thecat.js"></script> 
for all HTML files who uses this script
