### ISSUE TITLE
! BUG ! - HIGH PRIORITY - On deployed site, star icons are not being displayed. 

### ISSUE THREAD

**Issue by timsbootcamp** [timsbootcamp/meow-finder#76]
In code it is  lowercase ie : const imageStar = "./assets/images/star.png";
but physical file is 'Star.png'

Deployed Website url is : 

https://timsbootcamp.github.io/meow-finder/search.html
https://timsbootcamp.github.io/meow-finder/catalogue.html

**Comment by Khomych1004** [comment]
the error was in the css.
bug fixed
