### ISSUE TITLE
MEDIUM PRIORITY - I have added a meow sound when search results are being displayed. Your feedback on this ?

### ISSUE THREAD

**Issue by timsbootcamp** [timsbootcamp/meow-finder#78]
I have added a meow sound when search results are being displayed. Your feedback on this ?

Feel free to propose another sound as we are flexible.
Also, should we play the sound file here or when user clicks on cat icon next to menu.
We could even have it in both places. 
Your thoughts ?

**Comment by Khomych1004** [comment]
It sounds good

**Comment by timsbootcamp** [comment]
All complete
